S	0	508	*	*	*	*	*	KC861766;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aemula;	*
S	1	507	*	*	*	*	*	MG236070;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_populnea;	*
S	2	293	*	*	*	*	*	JN388079;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Drosophyllaceae,g:Drosophyllum,s:Drosophyllum_lusitanicum;	*
S	3	289	*	*	*	*	*	AB076240;tax=k:Viridiplantae,p:Streptophyta,c:Cycadopsida,o:Cycadales,f:Cycadaceae,g:Cycas,s:Cycas_micholitzii;	*
S	4	280	*	*	*	*	*	JN388060;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Droseraceae,g:Drosera,s:Drosera_chrysolepis;	*
S	5	278	*	*	*	*	*	MF785331;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Lamiales,f:Acanthaceae,g:Mendoncia,s:Mendoncia_hoffmannseggiana;	*
S	6	269	*	*	*	*	*	JN388067;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Droseraceae,g:Drosera,s:Drosera_indica;	*
S	7	269	*	*	*	*	*	OL537325;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Asparagales,f:Asparagaceae,g:Beschorneria,s:Beschorneria_rigida;	*
S	8	268	*	*	*	*	*	MF785426;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Salicaceae,g:Euceraea,s:Euceraea_sp._US:Redden7267;	*
S	9	268	*	*	*	*	*	MH763716;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Solanales,f:Solanaceae,g:Cuatresia,s:Cuatresia_plowmanii;	*
S	10	268	*	*	*	*	*	MK511103;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Poales,f:Poaceae,g:Cryptochloa,s:Cryptochloa_strictiflora;	*
H	10	268	100.0	+	0	0	=	MK511104;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Poales,f:Poaceae,g:Cryptochloa,s:Cryptochloa_strictiflora;	MK511103;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Poales,f:Poaceae,g:Cryptochloa,s:Cryptochloa_strictiflora;
S	11	263	*	*	*	*	*	KC861781;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_chrysocarpa;	*
S	12	263	*	*	*	*	*	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;	*
H	12	263	100.0	+	0	0	=	KC861796;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	11	263	100.0	+	0	0	=	KC861830;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_macracantha;	KC861781;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_chrysocarpa;
H	12	263	100.0	+	0	0	=	KC861868;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	12	263	100.0	+	0	0	=	KC861869;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	12	263	100.0	+	0	0	=	KC861871;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	12	263	100.0	+	0	0	=	KC861872;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	12	263	100.0	+	0	0	=	KC861873;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	12	263	100.0	+	0	0	=	KC861874;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
H	12	263	100.0	+	0	0	=	KC861875;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivularis;	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;
S	13	262	*	*	*	*	*	KC861768;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aquacervensis;	*
H	13	262	100.0	+	0	0	=	KC861769;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aquacervensis;	KC861768;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aquacervensis;
S	14	262	*	*	*	*	*	KC861811;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;	*
H	14	262	100.0	+	0	0	=	KC861812;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;	KC861811;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;
H	14	262	100.0	+	0	0	=	KC861813;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;	KC861811;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;
H	14	262	100.0	+	0	0	=	KC861815;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;	KC861811;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;
S	15	262	*	*	*	*	*	KC861844;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_monogyna_x_Crataegus_punctata;	*
H	13	262	100.0	+	0	0	=	KC861876;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_rivuloadamensis;	KC861768;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aquacervensis;
S	16	262	*	*	*	*	*	KC861881;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_spathulata;	*
S	17	262	*	*	*	*	*	KC861902;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_triflora;	*
H	13	261	99.6	+	0	0	52MI209M	KC861828;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_macracantha;	KC861768;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aquacervensis;
S	18	261	*	*	*	*	*	KP050142;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_mollis_x_Crataegus_viridis;	*
S	19	261	*	*	*	*	*	OL537373;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Lamiales,f:Acanthaceae,g:Elytraria,s:Elytraria_caroliniensis;	*
S	20	260	*	*	*	*	*	KC861767;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_almaatensis;	*
H	20	260	100.0	+	0	0	=	KC861851;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_pentagyna;	KC861767;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_almaatensis;
H	20	260	100.0	+	0	0	=	KC861853;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_pentagyna;	KC861767;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_almaatensis;
S	21	245	*	*	*	*	*	JN848164;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	*
H	21	245	100.0	+	0	0	=	JN848165;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848164;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	21	245	100.0	+	0	0	=	JN848166;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848164;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	21	245	100.0	+	0	0	=	JN848167;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848164;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
S	22	243	*	*	*	*	*	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	*
H	22	243	100.0	+	0	0	=	JN848176;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	243	99.6	+	0	0	243M	JN848261;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	243	99.6	+	0	0	243M	JN848262;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	242	99.6	+	0	0	222MI20M	JN848227;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	242	99.6	+	0	0	222MI20M	JN848230;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	242	99.6	+	0	0	222MI20M	JN848231;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	242	98.8	+	0	0	132MI110M	JN848259;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
H	22	242	98.8	+	0	0	132MI110M	JN848260;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;
S	23	241	*	*	*	*	*	MG234785;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_cilinodis;	*
H	23	241	100.0	+	0	0	=	MG237406;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_scandens;	MG234785;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_cilinodis;
S	24	237	*	*	*	*	*	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	*
H	24	237	99.2	+	0	0	237M	KC861774;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;
H	24	237	99.2	+	0	0	237M	KC861775;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;
H	24	237	99.2	+	0	0	237M	KC861776;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;
H	24	237	100.0	+	0	0	=	KC861777;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;
H	24	237	100.0	+	0	0	=	KC861778;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;
C	0	1	*	*	*	*	*	KC861766;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aemula;	*
C	1	1	*	*	*	*	*	MG236070;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_populnea;	*
C	2	1	*	*	*	*	*	JN388079;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Drosophyllaceae,g:Drosophyllum,s:Drosophyllum_lusitanicum;	*
C	3	1	*	*	*	*	*	AB076240;tax=k:Viridiplantae,p:Streptophyta,c:Cycadopsida,o:Cycadales,f:Cycadaceae,g:Cycas,s:Cycas_micholitzii;	*
C	4	1	*	*	*	*	*	JN388060;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Droseraceae,g:Drosera,s:Drosera_chrysolepis;	*
C	5	1	*	*	*	*	*	MF785331;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Lamiales,f:Acanthaceae,g:Mendoncia,s:Mendoncia_hoffmannseggiana;	*
C	6	1	*	*	*	*	*	JN388067;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Droseraceae,g:Drosera,s:Drosera_indica;	*
C	7	1	*	*	*	*	*	OL537325;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Asparagales,f:Asparagaceae,g:Beschorneria,s:Beschorneria_rigida;	*
C	8	1	*	*	*	*	*	MF785426;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Salicaceae,g:Euceraea,s:Euceraea_sp._US:Redden7267;	*
C	9	1	*	*	*	*	*	MH763716;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Solanales,f:Solanaceae,g:Cuatresia,s:Cuatresia_plowmanii;	*
C	10	2	*	*	*	*	*	MK511103;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Poales,f:Poaceae,g:Cryptochloa,s:Cryptochloa_strictiflora;	*
C	11	2	*	*	*	*	*	KC861781;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_chrysocarpa;	*
C	12	9	*	*	*	*	*	KC861795;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_erythropoda;	*
C	13	4	*	*	*	*	*	KC861768;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_aquacervensis;	*
C	14	4	*	*	*	*	*	KC861811;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_harbisonii;	*
C	15	1	*	*	*	*	*	KC861844;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_monogyna_x_Crataegus_punctata;	*
C	16	1	*	*	*	*	*	KC861881;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_spathulata;	*
C	17	1	*	*	*	*	*	KC861902;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_triflora;	*
C	18	1	*	*	*	*	*	KP050142;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_mollis_x_Crataegus_viridis;	*
C	19	1	*	*	*	*	*	OL537373;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Lamiales,f:Acanthaceae,g:Elytraria,s:Elytraria_caroliniensis;	*
C	20	3	*	*	*	*	*	KC861767;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_almaatensis;	*
C	21	4	*	*	*	*	*	JN848164;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	*
C	22	9	*	*	*	*	*	JN848173;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_multiflora;	*
C	23	2	*	*	*	*	*	MG234785;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Polygonaceae,g:Fallopia,s:Fallopia_cilinodis;	*
C	24	6	*	*	*	*	*	KC861773;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Rosales,f:Rosaceae,g:Crataegus,s:Crataegus_brachyacantha;	*
