S	0	483	*	*	*	*	*	KF694808;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Zingiberales,f:Zingiberaceae,g:Zingiber,s:Zingiber_officinale;	*
S	1	450	*	*	*	*	*	MH813137;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fabales,f:Fabaceae,g:Albizia,s:Albizia_lebbeck;	*
S	2	439	*	*	*	*	*	MH813133;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Apocynaceae,g:Catharanthus,s:Catharanthus_roseus;	*
S	3	431	*	*	*	*	*	MH813132;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Apocynaceae,g:Catharanthus,s:Catharanthus_roseus;	*
H	1	426	100.0	+	0	0	=	MH813137;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fabales,f:Fabaceae,g:Albizia,s:Albizia_lebbeck;	MH813137;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fabales,f:Fabaceae,g:Albizia,s:Albizia_lebbeck;
S	4	406	*	*	*	*	*	MH813130;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fagales,f:Juglandaceae,g:Pterocarya,s:Pterocarya_stenoptera;	*
S	5	405	*	*	*	*	*	MH813192;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malvales,f:Malvaceae,g:Helicteres,s:Helicteres_angustifolia;	*
S	6	400	*	*	*	*	*	MH813125;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Aleurites,s:Aleurites_moluccanus;	*
S	7	400	*	*	*	*	*	MH813208;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Solanales,f:Solanaceae,g:Nicotiana,s:Nicotiana_tabacum;	*
H	6	399	97.3	+	0	0	14M3D9MI6M2I18M2I12MD336M	MH813127;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Aleurites,s:Aleurites_moluccanus;	MH813125;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Aleurites,s:Aleurites_moluccanus;
S	8	398	*	*	*	*	*	MH813031;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Apocynaceae,g:Nerium,s:Nerium_oleander;	*
S	9	398	*	*	*	*	*	MH813034;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Lamiales,f:Scrophulariaceae,g:Buddleja,s:Buddleja_lindleyana;	*
S	10	396	*	*	*	*	*	MH813139;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Euphorbia,s:Euphorbia_tithymaloides;	*
S	11	395	*	*	*	*	*	MH813183;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Phytolaccaceae,g:Phytolacca,s:Phytolacca_americana;	*
S	12	393	*	*	*	*	*	MH813029;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Sapindales,f:Anacardiaceae,g:Toxicodendron,s:Toxicodendron_sylvestre;	*
S	13	378	*	*	*	*	*	MH813148;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Euphorbia,s:Euphorbia_antiquorum;	*
H	13	377	97.6	+	0	0	12MI339MD12MI13M	MH813150;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Euphorbia,s:Euphorbia_antiquorum;	MH813148;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Euphorbia,s:Euphorbia_antiquorum;
S	14	368	*	*	*	*	*	MH813124;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fabales,f:Fabaceae,g:Erythrophleum,s:Erythrophleum_fordii;	*
S	15	174	*	*	*	*	*	MH813116;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Gelsemiaceae,g:Gelsemium,s:Gelsemium_elegans;	*
C	0	1	*	*	*	*	*	KF694808;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Zingiberales,f:Zingiberaceae,g:Zingiber,s:Zingiber_officinale;	*
C	1	2	*	*	*	*	*	MH813137;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fabales,f:Fabaceae,g:Albizia,s:Albizia_lebbeck;	*
C	2	1	*	*	*	*	*	MH813133;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Apocynaceae,g:Catharanthus,s:Catharanthus_roseus;	*
C	3	1	*	*	*	*	*	MH813132;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Apocynaceae,g:Catharanthus,s:Catharanthus_roseus;	*
C	4	1	*	*	*	*	*	MH813130;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fagales,f:Juglandaceae,g:Pterocarya,s:Pterocarya_stenoptera;	*
C	5	1	*	*	*	*	*	MH813192;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malvales,f:Malvaceae,g:Helicteres,s:Helicteres_angustifolia;	*
C	6	2	*	*	*	*	*	MH813125;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Aleurites,s:Aleurites_moluccanus;	*
C	7	1	*	*	*	*	*	MH813208;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Solanales,f:Solanaceae,g:Nicotiana,s:Nicotiana_tabacum;	*
C	8	1	*	*	*	*	*	MH813031;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Apocynaceae,g:Nerium,s:Nerium_oleander;	*
C	9	1	*	*	*	*	*	MH813034;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Lamiales,f:Scrophulariaceae,g:Buddleja,s:Buddleja_lindleyana;	*
C	10	1	*	*	*	*	*	MH813139;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Euphorbia,s:Euphorbia_tithymaloides;	*
C	11	1	*	*	*	*	*	MH813183;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Caryophyllales,f:Phytolaccaceae,g:Phytolacca,s:Phytolacca_americana;	*
C	12	1	*	*	*	*	*	MH813029;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Sapindales,f:Anacardiaceae,g:Toxicodendron,s:Toxicodendron_sylvestre;	*
C	13	2	*	*	*	*	*	MH813148;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Malpighiales,f:Euphorbiaceae,g:Euphorbia,s:Euphorbia_antiquorum;	*
C	14	1	*	*	*	*	*	MH813124;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Fabales,f:Fabaceae,g:Erythrophleum,s:Erythrophleum_fordii;	*
C	15	1	*	*	*	*	*	MH813116;tax=k:Viridiplantae,p:Streptophyta,c:Magnoliopsida,o:Gentianales,f:Gelsemiaceae,g:Gelsemium,s:Gelsemium_elegans;	*
